### PR TITLE
Make git-clone faster by fetching only the last commit of SU2 and the submodules

### PR DESCRIPTION
**Pull request by martin-g**

### CODE REVIEW

**Review by pcarruscag — APPROVED** [review]

**Comment by martin-g** [comment]
@pcarruscag Since you like the idea of the shallow clone I pushed one more commit - delete any preexisting local clone of the repository. It is needed for the non-ephemeral self-hosted runners.

**Comment by pcarruscag** [comment]
:laughing: I don't even know what it does, but if it is a git feature... what can possibly go wrong.
More seriously maybe leave a comment in script explaining why those are needed.

**Comment by martin-g** [comment]
Added comments with explanations why the new shell commands have been added!
Please ask if something I do is not clear! :-)

**Comment by pcarruscag** [comment]
LGTM :+1: thanks

**Pull request merged**
