### PR TITLE
Update the base image to Ubuntu 20.04 so that it could be used for both amd64 and arm64 images

### PR DESCRIPTION
**Pull request by martin-g**
Set localtime to UTC so that the installation of tzdata do not ask for
selection.

### CODE REVIEW

**Comment by martin-g** [comment]
With these changes I was able to build a multi-platform image - https://github.com/users/martin-g/packages/container/package/su2code%2Fbuild-su2

What do you think about adding .github/workflows/docker-image-upload.yml that uses https://github.com/marketplace/actions/build-and-push-docker-images to build an image and push it to https://github.com/orgs/su2code/packages ?

Docker Hub is also an option but then someone will have to setup secrets for `docker login`. With ghrc.io the GITHUB_TOKEN can be used.

**Comment by pcarruscag** [comment]
It sounds like it would make our life easier whenever we want to update docker images, so I'm in favor.

**Comment by martin-g** [comment]
Working on it!

**Comment by martin-g** [comment]
The new workflow is added!
An admin will have to enable it!

**Comment by pcarruscag** [comment]
Hmmm I don't think I'm admin for this repo, where would I find the new workflow for approval?

**Comment by martin-g** [comment]
I am not quite sure!
At https://github.com/martin-g/SU2-Docker-Builds/actions I have only one failed execution complaining that `platforms` is not under `with`. I have fixed it and there was no another execution for this workflow ...

What do you see at https://github.com/su2code/Docker-Builds/actions ?

**Comment by martin-g** [comment]
Using 
```
push: 
  branches: 
    - "**" 
```
enabled it for my fork - https://github.com/martin-g/SU2-Docker-Builds/runs/6210959935?check_suite_focus=true! 
Let me fix this problem!

**Comment by martin-g** [comment]
Question: do you want the tag to be a date as before or `latest` is OK ?

**Comment by pcarruscag** [comment]
I think a date would be better, we could then test changes before running regression on a new image.
I see the default stuff:
image

**Comment by martin-g** [comment]
OK! I will change it to `date +%d%m%y`!

The workflow will appear once it is merged to `master` branch! 
For now it is only in my fork - https://github.com/martin-g/SU2-Docker-Builds/actions

**Comment by pcarruscag** [comment]
Cool thanks, let me know when you're ready and I'll merge the PR, we'll see if the workflow appears.

**Comment by martin-g** [comment]
@pcarruscag This PR is ready for review!

**Comment by martin-g** [comment]
It took me a while to figure out an issue with the permission to write the Docker package from the workflow.
At the end https://github.com/su2code/Docker-Builds/pull/1/files#diff-d130011db05f6b8224764d054b12e024eabe39d77d358324dd6f08b09591262fR3-R4 solved it!
I hope this will be enough for the push to `master`. But if it is not enough then we may need someone with admin rights for this repo to click few checkboxes in the Github UI.

**Comment by pcarruscag** [comment]
Alright, let's see if it works

**Comment by pcarruscag** [comment]
It's there https://github.com/su2code/Docker-Builds/actions/workflows/docker-image-upload.yml
Thanks for all the work! Please see if everything behaves as you expect.

**Comment by martin-g** [comment]
The workflow failed - https://github.com/su2code/Docker-Builds/actions/runs/2271410730
I'll send a new PR with improvements!

**Pull request merged**
